Add SHA256 checksum to install action.
The install action now supports a sha256 checksum of the resulting
binary. In the event that jetpack's devbox install script is
compromised, this will allow users to double check that the resulting
binary has a checksum configured at the github action level, potentially
preventing a breach of CI infrastructure.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,6 +14,8 @@ inputs:
   devbox-version: # version of the devbox cli
     description: 'Specify devbox CLI version you want to pin to. Default to latest'
     default: ''
+  sha256-checksum: # the expected SHA256 checksum of the devbox binary.
+    description: 'Specify an explicit checksum for the devbox binary. For extra security on top of the existing checks in the devbox launch script'
 
 runs:
   using: "composite"
@@ -65,6 +67,8 @@ runs:
     - name: Install devbox cli
       if: steps.cache-devbox-cli.outputs.cache-hit != 'true'
       shell: bash
+      env:
+        DEVBOX_SHA256: ${{ inputs.sha256-checksum}}
       run: |
         export DEVBOX_USE_VERSION="${{ env.latest_version }}"
         curl -fsSL https://get.jetpack.io/devbox | FORCE=1 bash
@@ -74,7 +78,25 @@ runs:
           echo "ERROR: mismatch devbox version downloaded. Expected $DEVBOX_USE_VERSION, got $version."
           exit 1
         fi
-        sudo mv ${HOME}/.cache/devbox/bin/${version}_*/devbox /usr/local/bin/devbox
+        DEVBOX_BINARY="$(find "${HOME}/.cache/devbox/bin" -name devbox)"
+        if [ -n "$DEVBOX_SHA256" ]; then
+          if command -v "sha256sum" 1>/dev/null 2>&1; then
+            DEVBOX_CHECKSUM="$(sha256sum "$DEVBOX_BINARY" | cut -f1 -d' ')"
+          elif command -v "shasum" 1>/dev/null 2>&1; then
+            DEVBOX_CHECKSUM="$(shasum -a 256 "$DEVBOX_BINARY" | cut -f1 -d' ')"
+          fi
+
+          if [ -z "$DEVBOX_CHECKSUM" ]; then
+            echo "ERROR: unable to get devbox checksum. Please ensure sha256sum or shasum is installed."
+            exit 2
+          fi
+
+          if [[ ! "$DEVBOX_CHECKSUM" = "$DEVBOX_SHA256" ]]; then
+            echo "ERROR: checksums do not match. Expected $DEVBOX_SHA256, got $DEVBOX_CHECKSUM."
+            exit 3
+          fi
+        fi
+        sudo mv "$DEVBOX_BINARY" /usr/local/bin/devbox
 
     - name: Install nix and devbox packages
       shell: bash
