Cache devbox cli, avoid github api rate limit

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,11 +18,6 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Install devbox
-      shell: bash
-      run: |
-        curl -fsSL https://get.jetpack.io/devbox | FORCE=1 bash
-  
     - name: Workaround for permission issue
       if: inputs.enable-cache == 'true'
       shell: bash
@@ -39,24 +34,53 @@ runs:
           /nix/var/nix
         key: ${{ runner.os }}-devbox-${{ hashFiles(format('{0}/devbox.json', inputs.project-path)) }}
 
-    - name: devbox version
-      id: devbox-version
-      if: inputs.devbox-version == ''
-      uses: pozetroninc/github-action-get-latest-release@v0.5.0
-      with:
-        repository: jetpack-io/devbox
-        excludes: prerelease, draft
-
-    - name: Install nix and devbox packages
+    - name: Get devbox version
       shell: bash
       env:
         DEVBOX_USE_VERSION: ${{ inputs.devbox-version }}
       run: |
+        if [[ -n $DEVBOX_USE_VERSION ]]; then
+          echo "latest_version=$DEVBOX_USE_VERSION" >> $GITHUB_ENV
+        else
+          tmp_file=$(mktemp)
+          latest_url="https://releases.jetpack.io/devbox/latest/version"
+          curl --fail --silent --location --output "${tmp_file}" "${latest_url}"
+          latest_version=$(cat "${tmp_file}")
+          if [[ -n ${latest_version} ]]; then
+            echo "Found devbox latest version ${latest_version}."
+            echo "latest_version=$latest_version" >> $GITHUB_ENV
+          else
+            echo "ERROR: unable to find the latest devbox version."
+            exit 1
+          fi
+        fi
+
+    - name: Mount devbox cli cache
+      id: cache-devbox-cli
+      uses: actions/cache@v3
+      with:
+        path: /usr/local/bin/devbox
+        key: ${{ runner.os }}-devbox-${{ env.latest_version }}
+
+    - name: Install devbox cli
+      if: steps.cache-devbox-cli.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        DEVBOX_USE_VERSION="${{ env.latest_version }}"
+        curl -fsSL https://get.jetpack.io/devbox | FORCE=1 bash
+
+        version=$(devbox version)
+        if [[ ! "$version" = "$DEVBOX_USE_VERSION" ]]; then
+          echo "ERROR: mismatch devbox version downloaded. Expected $DEVBOX_USE_VERSION, got $version."
+          exit 1
+        fi
+        sudo mv ${HOME}/.cache/devbox/bin/${version}_*/devbox /usr/local/bin/devbox
+
+    - name: Install nix and devbox packages
+      shell: bash
+      run: |
         NIX_INSTALLER_NO_CHANNEL_ADD=1
         NIX_BUILD_SHELL=/bin/bash
-        if [[ ! -n $DEVBOX_USE_VERSION ]]; then
-          DEVBOX_USE_VERSION=${{ steps.devbox-version.outputs.release }}
-        fi
         devbox shell --config=${{ inputs.project-path }} -- echo "Installing nix..." || true
         source /home/runner/.nix-profile/etc/profile.d/nix.sh
         devbox shell --config=${{ inputs.project-path }} -- echo "Installing packages..."
